[package]
name = "diesel_demo_step_1_sqlite"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2018"
publish = false

[dependencies]
diesel = { version = "2.0.0",  features = ["sqlite"] }
dotenvy = "0.15"

[[bin]]
name = "show_posts"
doc = false

[lib]
doc = false
