# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "workspace/web_edu/web_edu_lib/src/schema.rs"
[migrations_directory]
dir = "workspace/web_edu/web_edu_setup/migrations"
