[toolchain]
# channel = "stable-x86_64-unknown-linux-gnu"
channel = "stable-x86_64-pc-windows-gnu"
components = [ "rustfmt", "rustc-dev","clippy"]
targets = ["stable-x86_64-pc-windows-gnu" , "wasm32-unknown-unknown" ]
profile = "minimal"
