[package]
name = "web_edu_bin"
version = "0.1.0"
authors = ["Arman Riazi"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
doc = true
name = "web_edu_main"
path = "src/web_edu_main.rs"

[dependencies]
diesel = { version = "2.0.0", features = ["sqlite"] }
dotenvy = "0.15"
web_edu_model = { path = "../web_edu_model",  optional = false , default-features = true}
web_edu_lib = { path = "../web_edu_lib",  optional = false , default-features = true}
serde = { version = "1.0", features = ["derive"], optional = true , default-features = true}
serde_json="1.0.0"

[dev-dependencies]
diesel = "2.0.2"