[package]
name = "web_edu_bin"
version = "0.1.0"
authors = ["Arman Riazi"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web_edu_model = { path = "../web_edu_model",  optional = false , default-features = true}
web_edu_lib = { path = "../web_edu_lib",  optional = false , default-features = true}


[dev-dependencies]
diesel = "2.0.2"