[package]
name = "diesel_demo_step_2_mysql"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
diesel = { version = "2.0.0", path = "../../../diesel", features = ["mysql"] }
dotenvy = "0.15"

[[bin]]
name = "show_posts"
doc = false

[[bin]]
name = "write_post"
doc = false

[lib]
doc = false
