name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install Tokei      
      run: cargo install --git https://github.com/XAMPPRocky/tokei.git tokei
    - name: Print Tokei Report      
      run: tokei --sort code      
    - name: Run Program
      run: cargo run
